### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by yo-goto**
translation to Japanese
- Start here.md : completed
- Working with multiple notes.md : completed
- Index.md : not yet completed
- Obsidian.md : a little bit

### CODE REVIEW

**Comment by ericaxu** [comment]
Thank you for your work! <3

Would you like us to merge it now, or merge it later when it's ready? Thanks!

**Comment by yo-goto** [comment]
I've already translated some main documents ☺️
but I want to finish "How to" directory for the time being.
I'm going to revise my pull request after that.
then, please merge it.

**Comment by yo-goto** [comment]
I'm ready!! I've finished all of documentation other than updated and `Commercial license.md`
Please merge 😉

**Comment by yo-goto** [comment]
I'm going to create a new pull request because I've noticed I scattered commits by forced push. so please wait a while for merge.

**Comment by yo-goto** [comment]
I'm going to create a new pull request because I've noticed I scattered commits by forced push.

**Pull request closed without merging**
