### PR TITLE
Refactor front matter docs

### PR DESCRIPTION
**Pull request by marcusolsson**

### CODE REVIEW

**Comment by ericaxu** [comment]
I'm thinking we should just rename the "Front matter" doc to "Note metadata", what do you think?

**Comment by marcusolsson** [comment]
I like it! I think the Obsidian users that are familiar with the term "front matter" are limited, and metadata is a more recognizable term. 

Especially since we're already calling it metadata in the reading view:

Screenshot 2023-01-25 at 19 53 05

Though I think we should change the name of the editor setting in that case:

Screenshot 2023-01-25 at 19 53 20

Is there any other form of metadata in Obsidian? Would just "Metadata" be enough?

**Comment by kepano** [comment]
I agree with just saying "metadata" everywhere, we can reference the terms frontmatter/YAML inside the help docs text

**Comment by ericaxu** [comment]
Looks great!

**Pull request merged**
