### PR TITLE
Full documentation in Spanish was added.

### PR DESCRIPTION
**Pull request by taotomate**

### CODE REVIEW

**Comment by ericaxu** [comment]
Looks great! I assume the internal links all work when you view this folder as a vault?

**Comment by taotomate** [comment]
> Looks great! I assume the internal links all work when you view this folder as a vault?

Tetest it for yourself and tell me, on my machine it works hahaha. I hope it works well for everyone. Greetings!

**Comment by ericaxu** [comment]
Got it, thank you for your amazing work!

**Comment by taotomate** [comment]
> Got it, thank you for your amazing work!

Thanks to you too and to all the people who make Obsidian's existence possible, it's a fabulous app :-)

**Pull request merged**
