### PR TITLE
Create Getting started guides

### PR DESCRIPTION
**Pull request by marcusolsson**
This pull request adds the two pages for the Getting started docs:

- After reading **Create a vault** the reader should know how to:
  - Create a vault (but not necessarily understand the details)
- After **Create your first note** the reader should know how to:
  - Create a note
  - Use basic Markdown formatting
  - Switch between Editing and Reading views

These are intended to directly follow the installation guide and don't assume any previous knowledge about Obsidian.

## Considerations

- I've opted to use the keyboard shortcut (rather than using the File explorer) for creating a note, to shorten the time before the reader can start writing. 
- The Create your first note page aims to focus only on the note pane to limit the number of UI elements the user needs to interact with.

### CODE REVIEW

**Comment by ericaxu** [comment]
Looks good!

Now that live preview is publicly available, do you think we should update the last part in "Create your first note"?

**Comment by marcusolsson** [comment]
> Now that live preview is publicly available, do you think we should update the last part in "Create your first note"?

What part are you thinking about? Is it incorrect, or are you looking for more info on Live Preview specifically?

**Comment by ericaxu** [comment]
> > Now that live preview is publicly available, do you think we should update the last part in "Create your first note"?
> 
> What part are you thinking about? Is it incorrect, or are you looking for more info on Live Preview specifically?

Sorry, I meant that this part can incorporate live preview as an option since it's now publicly available: https://github.com/obsidianmd/obsidian-docs/pull/212/files#diff-9d2a9fb0e4cb5c9a86ac9a12b4d62acb27b26311fc1419804767a8c6bf00797fR27

Markdown syntax should be less of an issue for most people under Live Preview now.

**Comment by marcusolsson** [comment]
After thinking over this a bit, I don't think we need to explain the editing and reading views in the Getting started guide. Since Live Preview gives you both the editing and reading experience, you're less likely to switch between the views. Instead, I've added a paragraph on how the live preview works.

**Comment by marcusolsson** [comment]
I've added the Link notes guide to this pull request instead of creating a new one since they're part of the Getting started process.

**Comment by ericaxu** [comment]
Sorry for the late comment!

The link guide looks nice! One nit about the live preview part: although we eventually want to make Live Preview the default, it's still not the default right now. With a new brand vault, a user is shown the dialogue to promote Live Preview but they have to explicitly click the "Turn on Live Preview" to make it go in effect.

So the live preview part needs to be tweaked if I were to merge it now. Otherwise I can wait until Live Preview is default to merge it, but I don't know how long that would take.

**Comment by marcusolsson** [comment]
I deleted the note on live preview for now, and rebased the changes.

**Comment by ericaxu** [comment]
Merged and published!

**Pull request merged**
