### PR TITLE
"Danish" docs ready for pull. 100% translated

### PR DESCRIPTION
**Pull request by henrikfalk**
Created Danish document structure aligned with the Danish language version of Obisidian.
"da" docs updated with last changes in "en" docs
Status: 4 of 93 files translated.

### CODE REVIEW

**Comment by ericaxu** [comment]
Looking good!

Let me know when it's ready so we can pull it in.

**Comment by henrikfalk** [comment]
You can pull it in because it is important re-translations to some core functions.
I found better and more correct wording in the app  in my process of translating the docs.

**Comment by henrikfalk** [comment]
@ericaxu All the docs are translated to Danish + all relevant images. You can pull nov :)

**Comment by ericaxu** [comment]
> @ericaxu All the docs are translated to Danish + all relevant images. And everything is updated with latest changes in "en" docs.
> You can pull now :)

That's such an achievement! We'll package it up so that users who have their language set to Danish can see this when they open help soon.

Thanks again!

**Pull request merged**
