### PR TITLE
Update docs for Outline and Page preview plugins

### PR DESCRIPTION
**Pull request by marcusolsson**
Only minor style issues here. Also, I went ahead and removed the screenshot for consistency.

### CODE REVIEW

**Comment by ericaxu** [comment]
We should address this issue in this PR: https://github.com/obsidianmd/obsidian-docs/issues/271

**Comment by ericaxu** [comment]
For page preview, I think it's worth it to explain the settings can let you customize ctrl/cmd-hover behavior. What do you think?

**Comment by lishid** [comment]
I think we'll want to add a bit to Page Preview since it can also preview anywhere that has a file object like file explorer, search results, backlinks, etc.

**Comment by marcusolsson** [comment]
> it can also preview anywhere that has a file object like file explorer, search results, backlinks, etc.

I had no idea! Definitely good things to add!

**Pull request merged**
