### PR TITLE
Plugins french translation

### PR DESCRIPTION
**Pull request by Fabien-jrt**
# French plugins translation.
The french translation of the `Plugins` files.

**File names are not renamed yet, to avoid broken links.**

## Related to
#7:  as it's a french translation of `How to` and `Advance use`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Great work! Let me know when it's ready for merging.

**Comment by Fabien-jrt** [comment]
> Great work! Let me know when it's ready for merging.

Thank you! I will mention you when it's ready.

**Comment by Fabien-jrt** [comment]
@ericaxu, it's ready! 👍

**Comment by ericaxu** [comment]
Thank you for your amazing work!

**Comment by Fabien-jrt** [comment]
> Thank you for your amazing work!

Thank you for your amazing app!  😉

**Pull request merged**
