### PR TITLE
ru: Translation updated and completed (major update)

### PR DESCRIPTION
**Pull request by JxhnnyUt8h**
Translation updated and completed for Russian Help:

- Translation updated to current English version
- Screenshots updated with Russian versions
- Russian help site can be published from now

Not sure that it can be reviewed in one round, but it can be fixed later of course ;)

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for the big update!

Let me know if anyone wants to review this. If not we'll merge in a few days.

**Comment by w0rm49** [comment]
Checked the diffs briefly, good additions, besides the new translated pages, many typos and bad forms were fixed.
lgtm

**Review by ryjjin — APPROVED** [review]
I finally went through all the edits. Awesome, titanic work.

I only have questions about the names of some plugins and the translation of the words "panels", "workspaces" and possibly a couple of technical terms, but these are questions for translation in the Russian-speaking community as a whole (Johnny's translation is now consistent with the translation of the application). And it's definitely not a question of taking current results into production :)

**Comment by ericaxu** [comment]
Thank you for your amazing work!

**Pull request merged**
