### PR TITLE
kanban, yaml, css and mathjax

### PR DESCRIPTION
**Pull request by archelpeg**
- I've updated the change from `base mode` to `base theme`
- CSS themes/snippets is updated
- how to link to notes in mermaid/use special characters
- link to mathjax and supported packages
- supported yaml keys
- added kanban note under advanced topics that explains how imdone can be used together with Obsidian

Apart from the first bullet point these were topics that came up repeatedly on the Discord in the last month or two.

### CODE REVIEW

**Comment by archelpeg** [comment]
I've also removed the legacy way with `obsidian.css`.

**Comment by archelpeg** [comment]
Concerning the reference to imdone I've added, the spectrum theme supports kanban boards now. (Visually in preview mode, the cards are moved around by editing the list in a note with the cssclass kanban.) 

And Liam is working on a plugin.

I think there should still be a reference to imdone, but perhaps also how to do it in CSS and tell people about the plugin, once it's released.

**Comment by ericaxu** [comment]
Thank you so much!

Really appreciate the detailed update.

One small thing: we'd prefer not to endorse any specific third-party, non-community solution. It would be great to include Spectrum (or the link to the snippet if available) and the plugin once they are available. For now I think it's best if we hold off the kanban view article.

What do you think?

**Comment by archelpeg** [comment]
I've removed the kanban page. I think you're right, the help docs should only list core features.
Everything else, including plugins and custom themes, should find its place in the forum. I've posted my (edited) kanban note as an answer to a question in the forum so that people may make use of it there.

I've also added the `{{title}}` variable to the templates section.

**Comment by ericaxu** [comment]
Looks good to me! Thank you so much for the work. I think the new additions are going to be super helpful, especially the part about Mermaid and MathJax!

**Pull request merged**
