### PR TITLE
First batch of Obsidian v1.x Danish docs ready for merge!

### PR DESCRIPTION
**Pull request by henrikfalk**
Please do not merge before I notify!
This is the first batch of new docs.

### CODE REVIEW

**Comment by ericaxu** [comment]
Just to confirm, is this ready for merging?

**Comment by henrikfalk** [comment]
No, I need a week more to wrap up :) I write a comment when I am ready.

**Comment by henrikfalk** [comment]
You can merge now :)
I will translate Sync and Publish and the rest along the way :)

**Comment by ericaxu** [comment]
Thank you so much for your work!

**Pull request merged**
