### PR TITLE
✏️ WIP: Update en/ ✏️

### PR DESCRIPTION
**Pull request by fibretothepremises**
Add headings, sections & svg icons, update attachments, fix typos & broken links, and improve readability and conciseness.

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for the PR!

I can't view binary changes on GitHub, what changes did you make to the png files?

Also re: svg icons inline, I think that would make it easier to find those buttons, but in the meantime making source really unreadable. Maybe we can use png images instead? I think in the newest version inline embed images should work.

**Comment by fibretothepremises** [comment]
### RE: Binary files
They are updated as the deleted ones show old UI. Also to assist users through stepped guides, I took some new screenshots. You should be able to view them by going into the "Files changed" tab and clicking the horizontal ellipsis on the right for each file as shown in attached image. If not, they are available in the [Attachments folder in my forked-repo](https://github.com/fibretothepremises/obsidian-docs/tree/master/en/Attachments).
view-file

### RE: SVG icons
Yeah, I agree. The png icons are a work-around but I don't think it scales well if you mean to use the `![[]]` syntax. Is there a way to manually size it? I'm not sure what the best practice would be here. Let me know if you'd like to go ahead with the SVG icons, otherwise, I'm happy to embed block-level screenshots (as long as there are no major UI updates coming soon). Personally, I think it's worth the devs' sacrifice for the sake of the users.

**Comment by fibretothepremises** [comment]
_Update Feb 10:_ 
### Versions
1. **Reference Vault** (As is - alphabetically ordered)
- Keep folder and note names as is. For quick referencing using search function. **User Story**: an experienced user wants to quickly remember how to resize images => search "resize"
2. **Stepped Vault** (Numbered)
- Prefix folder and note names by numbers. **User Story 1**: a new user wants to learn how to use the app through a tutorial-like structure => e.g. start from 01 - Quick Start => learn 02 - Fundamental Commands etc. **User Story 2**: finished learning fundamental commands and made a few notes. Now, wants to learn more advanced topics => learn 05 - Advanced Topics etc.

### Button Icons
- **Local:** Do **not** use SVG icons for user readability.
- **Local:** Do **not** use PNG icons to avoid inconsistency with changing themes.
png-inconsistency-dark
png-inconsistency-light

- **Local:** **SOLUTION** - Use descriptive language and maybe screenshots.
- **Web:** Use SVG icons at https://publish.obsidian.md/help as it is viewed exclusively in preview mode

### Stepped Guides
- Implement stepped guides in all "How To" notes, if possible, by using numbered lists
stepped-guide-audio-recorder

**Comment by ericaxu** [comment]
> Web: Use SVG icons at https://publish.obsidian.md/help as it is viewed exclusively in preview mode

Not sure if this is possible as we directly publish from `en/` to the site... 🤔

**Comment by fibretothepremises** [comment]
> > Web: Use SVG icons at https://publish.obsidian.md/help as it is viewed exclusively in preview mode
> 
> Not sure if this is possible as we directly publish from `en/` to the site... 🤔

The en/ folder with SVG icons will live purely on here. i.e. the users will never run into seeing lines of SVG code (only the devs will. And I personally think it's worth the devs' sacrifice for the users' sake). Since, I have proposed separate vaults of Obsidian Docs to live locally on users' systems, if you decide to take this approach the end user will never see SVG code (only the devs will while changing updating the en/ docs that live here, in the base-repo)

Either case, I will develop a couple of different version of the Help docs. It's up to you guys whether you'd like to pull them at the end of the day.

**Comment by ericaxu** [comment]
> Either case, I will develop a couple of different version of the Help docs. It's up to you guys whether you'd like to pull them at the end of the day.

Thanks, got it.

Maybe I didn't make myself clear, but we don't keep different versions of docs for online and local yet. Maybe that's a good idea, but right now it's the same version. The only difference is that the hosted version has an additional `Index` file, I believe.

**Comment by fibretothepremises** [comment]
> > Either case, I will develop a couple of different version of the Help docs. It's up to you guys whether you'd like to pull them at the end of the day.
> 
> Thanks, got it.
> 
> Maybe I didn't make myself clear, but we don't keep different versions of docs for online and local yet. Maybe that's a good idea, but right now it's the same version. The only difference is that the hosted version has an additional `Index` file, I believe.

Storing different versions is probably not needed as it's mainly for the idea of having SVG icons displayed on the hosted version and not have it distract users in-app.

I will close this PR for now as it may be a while for me to catch up with you guys implementing new features so frequently!

Thanks for the feedback

**Comment by ericaxu** [comment]
Thanks for all the work, and I think the step-by-step guides and icons look really good once functionality stablizes!

**Pull request closed without merging**
