### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by yo-goto**
I've completed Japanese translation!! 
I'm not familiar with git flow and there was something wrong with the previous commit.
so I made a totally new pull request for Japanese translation. 
About the correspondence table for file names, please see Japanese translation issue.

### CODE REVIEW

**Comment by yo-goto** [comment]
The current state of translation process is up-to-date as of 2020-11-30 except for image files in Attachments folder.

**Comment by yo-goto** [comment]
Now, everything about Japanese translation is up-to-date and completed.

**Comment by ericaxu** [comment]
That's amazing! Thank you so much! <3

**Comment by ericaxu** [comment]
Be sure to add your name to the credits page! <3

**Pull request merged**
